# paper: "/home/valis/resources/backgrounds/okuusplosion.png"
# paper: "/home/valis/resources/backgrounds/tenshi-rock.jpg"
# paper: "/home/valis/resources/backgrounds/aya-shrine.png"
paper: "/home/valis/resources/backgrounds/texas.jpg"
# paper: "/home/valis/resources/backgrounds/machinations.jpg"
# paper: "/home/valis/resources/backgrounds/indoor-forest.png"
# paper: "/home/valis/resources/backgrounds/sanaelake.jpg"
# bar-size: 0.8
bar-size: 1
